#Kabanero! on activate substitute kaberno-collection for text 'kaberno-collection'
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: kaberno-collection-build-deploy-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  tasks:
    - name: build-task
      taskRef:
        name: kaberno-collection-build-task
      resources:
        inputs:
        - name: git-source
          resource: git-source
        outputs:
        - name: docker-image
          resource: docker-image
    - name: deploy-task
      taskRef:
        name: kaberno-collection-deploy-task
      runAfter: [build-task]
      resources:
        inputs:
        - name: git-source
          resource: git-source
        - name: docker-image
          resource: docker-image
