apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: docker-build-deploy
spec:
  resources: 
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: build
    taskRef:
      name: docker-build-push
    resources:
      inputs:
      - name: git-source
        resource: git-source
      outputs:
      - name: container-name
        resource: docker-image
  - name: deploy
    runAfter: [build]
    taskRef: 
      name: deploy-using-kubectl-task
    resources: 
      inputs:
      - name: git-source
        resource: git-source 
      - name: container-name
        resource: docker-image