apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: fast-build
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
    - name: pathToDockerFile
      description: The path to the dockerfile to build
      default: ./git-source/Dockerfile
    - name: pathToContext
      description: The build context used by Kaniko (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: ./git-source
  outputs:
    resources:
      - name: container-name
        type: image
  steps:
  - name: show-image-name
    image: docker.io/ubuntu
    command: ['/bin/bash'] 
    args: ['-c', 'echo build-push $IMG'] 
    env:
      - name: IMG
        value: ${outputs.resources.container-name.url}
  - name: build
    image: docker
    command:
    - docker 
    args:
    - 'build'
    - '-f'
    - ${inputs.params.pathToDockerFile}
    - '-t'
    - ${outputs.resources.container-name.url}
    - ${inputs.params.pathToContext}
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  - name: push 
    image: docker
    command:
    - docker 
    args:
    - 'push'
    - ${outputs.resources.container-name.url}
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket