apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: single-pass-build-deploy
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
    - name: pathToDockerFile
      description: The path to the dockerfile to build
      default: ./git-source/Dockerfile
    - name: pathToContext
      description: The build context used by Kaniko (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
      default: ./git-source
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
  - name: show-image-name
    image: docker.io/ubuntu
    command: ['/bin/bash'] 
    args: ['-c', 'echo build-push $IMG'] 
    env:
      - name: IMG
        value: ${outputs.resources.builtImage.url}
  - name: build
    image: docker
    command:
    - docker 
    args:
    - 'build'
    - '-f'
    - ${inputs.params.pathToDockerFile}
    - '-t'
    - ${outputs.resources.builtImage.url}
    - ${inputs.params.pathToContext}
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
  - name: push 
    image: docker
    command:
    - docker 
    args:
    - 'push'
    - ${outputs.resources.builtImage.url}
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket
  - name: show-image-name2
    image: docker.io/ubuntu
    command: ['/bin/bash'] 
    args: ['-c', 'echo deploy-using-kubectl-task  $IMG'] 
    env:
      - name: IMG
        value: ${outputs.resources.builtImage.url}
  - name: modify-yaml
    image: ubuntu
    command: ['/bin/bash']
    args: ['-c', 'find ./git-source/config -type f -exec sed -i -e s!"image: PIPELINE_REPLACE:latest"!"image: ${IMG}"!g {} \;']
    env:
      - name: IMG
        value: ${outputs.resources.builtImage.url}
  - name: show-config
    image: docker.io/ubuntu
    command: ['/bin/bash'] 
    args: ['-c', 'cat ./git-source/config/*'] 
    env:
      - name: IMG
        value: ${outputs.resources.builtImage.url}
  - name: install-new
    image: lachlanevenson/k8s-kubectl
    command: ['kubectl']
    args: 
    - 'apply'
    - '-f'
    - './git-source/config'
  - name: pipeline-run-summary
    image: jduimovich/summary 
    workingDir: "/workspace/git-source/"
    command: ['bash'] 
    args: ['/script.sh']
    env:
      - name: REPO
        value: ${inputs.resources.git-source.url}
      - name: IMAGE
        value: ${outputs.resources.builtImage.url}
      - name: DEPLOY
        value: "/workspace/git-source/config"


    