apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tekton-basic-pipeline
spec:
  tasks:
  - name: task-1
    taskRef:
      name: tekton-basic-task
  - name: task-2
    runAfter: [task-1]
    taskRef:
      name: tekton-basic-task
  - name: task-3
    runAfter: [task-2]
    taskRef:
      name: tekton-basic-task
