#!/bin/bash
script="$0"
script_dir="$(dirname $script)"
script_name="$(basename $script)"

GIT_URL=$1 
GIT_REPO_BASE=$(basename $GIT_URL .git )
DOCKER_IMAGE=$GIT_REPO_BASE
GIT_SRC_RES=run0-git-source-$GIT_REPO_BASE
TAG=$(date +"%y%m%d%H%M%S")
P_REF=pipeline0
if [ -z $2 ]
then
PIPE_DIR=pipelines 
else  
PIPE_DIR=$2 
fi

INPUT_TEMPLATE=$script_dir/p0-pipeline-run

PIPELINE_RUN="$(mktemp)"  

printf "%-20s %s\n"  "Pipeline Name:" $P_REF 
printf "%-20s %s\n"  "Repository:" $GIT_URL 
printf "%-20s %s\n"  "Directory:"  $PIPE_DIR 
printf "%-20s %s\n"  "Service Account:" $TEKTON_DEMO_SA 
printf "%-20s %s\n"  "Namespace:" $TEKTON_DEMO_NS 

sed  "s!PRUN_NAME!$script_name-$TAG!;s!P_SA!$TEKTON_DEMO_SA!;s!P_REF!$P_REF!;s!GIT_URL!$GIT_URL!;s!DOCKER_IMAGE!$DOCKER_IMAGE!;s!GIT_SRC_RES!$GIT_SRC_RES!;s!PIPE_DIR!$PIPE_DIR!;s!TARGET_NS!$TEKTON_DEMO_NS!" <$INPUT_TEMPLATE > $PIPELINE_RUN 
kubectl apply -f $PIPELINE_RUN -n $TEKTON_DEMO_NS
 
#cat  $PIPELINE_RUN  


