#!/bin/bash
script="$0"
script_dir="$(dirname $script)"

if [ -z $1 ]
then
PIPE_DIR=pipelines 
else  
PIPE_DIR=$1 
fi

if [ -d $PIPE_DIR ]
then
echo Installing pipelines contents via pipeline0 directory $PIPE_DIR
else 
echo This directory has no $PIPE_DIR directory, exiting
exit
fi

sh $script_dir/run-p0-pipeline $($script_dir/git-repo-url) $1